name: Website CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**' # ONLY trigger if files in the frontend folder change
  
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Upload to Azure Storage'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name streschallenge022025v2 \
              --auth-mode login \
              -d '$web' \
              -s ./frontend \
              --overwrite